### ISSUE TITLE
Cannot build with GHC 9.8

### ISSUE THREAD

**Issue by ocharles** [morpheusgraphql/morpheus-graphql#854]
I get the following error with `morpheus-graphql-code-gen-utils`:

```
[6 of 7] Compiling Data.Morpheus.CodeGen.TH ( src/Data/Morpheus/CodeGen/TH.hs, dist/build/Data/Morpheus/CodeGen/TH.o, dist/build/Data/Morpheus/CodeGen/TH.dyn_o )
 
src/Data/Morpheus/CodeGen/TH.hs:290:54: error: [GHC-83865]
    • Couldn't match type ‘()’ with ‘BndrVis’
      Expected: [TyVarBndr BndrVis]
        Actual: [TyVarBndr ()]
    • In the second argument of ‘TySynD’, namely ‘(toTypeVars params)’
      In the expression: TySynD (toName name) (toTypeVars params)
      In an equation for ‘printTypeSynonym’:
          printTypeSynonym name params
            = TySynD (toName name) (toTypeVars params)
    |
290 | printTypeSynonym name params = TySynD (toName name) (toTypeVars params)
    |                                                      ^^^^^^^^^^^^^^^^^
 
src/Data/Morpheus/CodeGen/TH.hs:349:10: error: [GHC-83865]
    • Couldn't match type ‘()’ with ‘BndrVis’
      Expected: [TyVarBndr BndrVis]
        Actual: [TyVarBndr ()]
    • In the third argument of ‘DataD’, namely
        ‘(toTypeVars $ map toName $ typeParameters cgTypeName)’
      In the second argument of ‘($)’, namely
        ‘DataD
           [] (toName cgTypeName)
           (toTypeVars $ map toName $ typeParameters cgTypeName) Nothing
           (map printConstructor cgConstructors)
           [printDerivClause cgDerivations]’
      In the expression:
        pure
          $ DataD
              [] (toName cgTypeName)
              (toTypeVars $ map toName $ typeParameters cgTypeName) Nothing
              (map printConstructor cgConstructors)
              [printDerivClause cgDerivations]
    |
349 |         (toTypeVars $ map toName $ typeParameters cgTypeName)
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
